debian musl llvm build - try fixing missing clang header [failed]
```
In file included from /home/runner/work/curl-for-win/curl-for-win/zstd/lib/common/error_private.c:13:
In file included from /home/runner/work/curl-for-win/curl-for-win/zstd/build/cmake/../../lib/common/error_private.h:25:
/home/runner/work/curl-for-win/curl-for-win/zstd/build/cmake/../../lib/common/compiler.h:209:14: fatal error: 'emmintrin.h' file not found
             ^~~~~~~~~~~~~
1 error generated.
```