extend musl llvm `LDFLAGS` to DLLs and by default to all executables
"all executables" include the easily forgotten ones built by autotools
configure phase, even when not building any actual useful executable
for an autotools project (only static libs, like we do here in most
cases). To have `./configure` test results consistent with build-time
behaviour, we must always populate `LDFLAGS` and `LIBS` with custom
options. We use global custom options to override glibc and libgcc for
debian llvm musl builds.

Option mismatch at detection and use manifested in this build issue for
example, when building libressl (arc4random_buf detected in configure
with glibc, but indeed missing because of using musl headers. configure
doesn't need this declared in the headers (only libs!) to detect it
successfully):
```
../../crypto/bn/bn_rand.c:153:2: error: call to undeclared function 'arc4random_buf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        arc4random_buf(buf, bytes);
        ^
```

This also fixes these warnings with autotools debian llvm musl builds:
```
configure: LDFLAGS note: LDFLAGS should only be used to specify linker flags, not libraries. Use LIBS for: -lc
configure: LDFLAGS note: LDFLAGS should only be used to specify linker flags, not libraries. Use LIBS for: -lclang_rt.builtins-aarch64
```